# Generated by Django 3.1.3 on 2023-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.AddField(
            model_name='question',
            name='question_grade',
            field=models.IntegerField(default=0),
        ),
    ]
