# Generated by Django 3.1.3 on 2023-02-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230203_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choices',
        ),
        migrations.AddField(
            model_name='submission',
            name='chocies',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
